# Fișier de configurare pentru mediul de testare
env: "staging"

service:
  name: "JSONPLACEHOLDER API"
  baseUrl: "https://jsonplaceholder.typicode.com/todos/1"

timeouts:
  connect: 5000   # 5 secunde
  read: 10000     # 10 secunde