# Fișier de configurare pentru mediul de testare
env: "staging"

service:
  name: "Hapifyme API"
  baseUrl: "https://apps.qualiadept.eu/hapifyme"

timeouts:
  connect: 5000   # 5 secunde
  read: 10000     # 10 secunde